import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/header/Header";
import Providers from "./providers";
import ConsultModal from "@/components/modals/ConsultModal";
import ConsultToast from "@/components/ui/ConsultToast";
const palatino = localFont({
  src: [
    {
      path: "/fonts/palatinolinotype_roman.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/palatinolinotype_italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "/fonts/palatinolinotype_bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "/fonts/palatinolinotype_bolditalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-palatino",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${palatino.variable} antialiased`}>
        <Providers>
          <Header />
          {children}
          <Footer />
          <ConsultModal />
          <ConsultToast />
        </Providers>
      </body>
    </html>
  );
}
